server:
  port: 8081
topic:
  name: t.meal


spring:
  Kafka:
    consumer:
      group-id: "default"
      bootstrap-servers: 'Kafka:29092'
  datasource:
     url:jdbc:mysql: //mysql-db:3306/Meal_db?useSSL=false
     username: root
     password: 1234
  jpa:
    properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto=update


